<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
		<td valign="top" width="715"><h1>Pantai Pasir Merah  </h1>
		  <p>h pantai merah ini sama dengan pantai pink (pink beach) yang disebut-sebut sebagai satu dari tiga pantai yang berpasir merah di dunia. Tapi tidak seperti dugaanku, Pantai Merah ini ternyata lokasinya tidak jauh dari dermaga Komodo dan masih dalam lintasan yang harus dilewati jika ingin ke Pulau Komodo. Air di perairan ini sangat tenang, namun sayangnya saat itu ternyata air baru pada posisi masih pasang. Terumbu karang berada di kedalaman empat sampai lima meter, dan yang paling menyulitkan adalah saat itu terjadi arus yang cukup kuat ke tengah di sisi selatan perairan. Hal itu aku rasakan saat aku dan Angga mencoba mencapai terumbu karang dari sisi selatan, tanpa bergerak ternyata badan kami terseret ke tengah dengan cepat. Menyadari situasi ini aku segera ke pinggir pantai setelah memberikan kode ke Angga untuk tidak ke pinggir juga. Angga sendiri sebenarnya ini menjadi pengalaman pertama snorklingnya, kondisi perairan seperti ini jelas berbahaya untuknya. <br />
		    Walaupun saat ini siang hari dan cuaca terasa sangat panas, namun sebaliknya air yang mengalir jernih justru terasa dingin, kontras sekali. Mungkin pengaruh pergerakan arus di sini yang menyebabkan suhu air dingin.<br />
		    Perahu kami tak bisa ke pinggir pantai, menurut aturan dari petugas Taman Nasional Komodo memang perahu besar dilarang ke pinggir pantai dan hanya menambatkan perahunya di tengah, untuk ke pantai harus dengan perahu kecil atau dengan motor boat yang biasanya dibawa serta di perahu besar. Sayang perahu kami tidak memiliki perahu kecil seperti yang digunakan para bule yang sekarang dengan kameranya asyik naik di atas motor boat ke pinggir pantai.<br />
	      Pantai merah ini memang punya kawasan terumbu yang indah, jika beruntung bahkan kita bisa melihat Manta Ray, ikan pari raksasa dengan kepala terbelah dua. Kawasan pantai berpasir putih dengan aksen merah, yang rupanya berasal dari remukan terumbu karang merah yang telah mati. Kami hanya berenang sebentar di pantai merah karena posisi matahari yang berada di atas kepala terasa keras menyengat, sementara dari perhitungan pak Tayeb kami masih bisa singgah di Pulau Kanawa jika berangkat saat ini.</p>
    </td>
</tr>
</table>
